[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counterapp = "CCYjThsz99xQE1T97EzcsCJUav4q5KvpFtYUiUzY7HEo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "target/deploy/counterapp-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
